name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  core-tests:
    name: Core Library Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: readap
    - name: Run core library tests
      run: cargo test --manifest-path readap/Cargo.toml --verbose
    - name: Run clippy on core
      run: cargo clippy --manifest-path readap/Cargo.toml -- -D warnings

  wasm-build:
    name: WASM Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: readap-wasm
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build WASM package
      run: wasm-pack build readap-wasm --target web
    - name: Check WASM clippy (allow warnings for now)
      run: cargo clippy --manifest-path readap-wasm/Cargo.toml --target wasm32-unknown-unknown || true

  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - name: Check formatting
      run: cargo fmt --all -- --check